function sw(a){
    switch (a) {
        case '0': return '-webkit-linear-gradient(right,white 100%, #709daf 0%)'; break; 
        case '1': return '-webkit-linear-gradient(right,white 99%, #709daf 1%)'; break;
        case '2': return '-webkit-linear-gradient(right,white 98%, #709daf 2%)'; break;
        case '3': return '-webkit-linear-gradient(right,white 97%, #709daf 3%)'; break;
        case '4': return '-webkit-linear-gradient(right,white 96%, #709daf 4%)'; break;
        case '5': return'-webkit-linear-gradient(right,white 95%, #709daf 5%)';break;
        case '6': return '-webkit-linear-gradient(right,white 94%, #709daf 6%)'; break;
        case '7': return '-webkit-linear-gradient(right,white 93%, #709daf 7%)'; break;
        case '8': return '-webkit-linear-gradient(right,white 92%, #709daf 8%)'; break;
        case '9': return '-webkit-linear-gradient(right,white 91%, #709daf 9%)'; break;
        case '10': return '-webkit-linear-gradient(right,white 90%, #709daf 10%)'; break;
        case '11': return '-webkit-linear-gradient(right,white 89%, #709daf 11%)'; break;
        case '12': return '-webkit-linear-gradient(right,white 88%, #709daf 12%)'; break;
        case '13': return '-webkit-linear-gradient(right,white 87%, #709daf 13%)'; break;
        case '14': return '-webkit-linear-gradient(right,white 86%, #709daf 14%)'; break;
        case '15': return '-webkit-linear-gradient(right,white 85%, #709daf 15%)';break;
        case '16': return '-webkit-linear-gradient(right,white 84%, #709daf 16%)'; break;
        case '17': return '-webkit-linear-gradient(right,white 83%, #709daf 17%)'; break;
        case '18': return '-webkit-linear-gradient(right,white 82%, #709daf 18%)'; break;
        case '19': return '-webkit-linear-gradient(right,white 81%, #709daf 19%)'; break;
        case '20': return '-webkit-linear-gradient(right,white 80%, #709daf 20%)'; break;
        case '21': return '-webkit-linear-gradient(right,white 79%, #709daf 21%)'; break;
        case '22': return '-webkit-linear-gradient(right,white 78%, #709daf 22%)'; break;
        case '23': return '-webkit-linear-gradient(right,white 77%, #709daf 23%)'; break;
        case '24': return '-webkit-linear-gradient(right,white 76%, #709daf 24%)'; break;
        case '25': return '-webkit-linear-gradient(right,white 75%, #709daf 25%)';break;
        case '26': return '-webkit-linear-gradient(right,white 74%, #709daf 26%)'; break;
        case '27': return '-webkit-linear-gradient(right,white 73%, #709daf 27%)'; break;
        case '28': return '-webkit-linear-gradient(right,white 72%, #709daf 28%)'; break;
        case '29': return '-webkit-linear-gradient(right,white 71%, #709daf 29%)'; break;
        case '30': return '-webkit-linear-gradient(right,white 70%, #709daf 30%)'; break;
        case '31': return '-webkit-linear-gradient(right,white 69%, #709daf 31%)'; break;
        case '32': return '-webkit-linear-gradient(right,white 68%, #709daf 32%)'; break;
        case '33': return '-webkit-linear-gradient(right,white 67%, #709daf 33%)'; break;
        case '34': return '-webkit-linear-gradient(right,white 66%, #709daf 34%)'; break;
        case '35': return '-webkit-linear-gradient(right,white 65%, #709daf 35%)';break;
        case '36': return '-webkit-linear-gradient(right,white 64%, #709daf 36%)'; break;
        case '37': return '-webkit-linear-gradient(right,white 63%, #709daf 37%)'; break;
        case '38': return '-webkit-linear-gradient(right,white 62%, #709daf 38%)'; break;
        case '39': return '-webkit-linear-gradient(right,white 61%, #709daf 39%)'; break;
        case '40': return '-webkit-linear-gradient(right,white 60%, #709daf 40%)'; break;
        case '41': return '-webkit-linear-gradient(right,white 59%, #709daf 41%)'; break;
        case '42': return '-webkit-linear-gradient(right,white 58%, #709daf 42%)'; break;
        case '43': return '-webkit-linear-gradient(right,white 57%, #709daf 43%)'; break;
        case '44': return '-webkit-linear-gradient(right,white 56%, #709daf 44%)'; break;
        case '45': return '-webkit-linear-gradient(right,white 55%, #709daf 45%)';break;
        case '46': return '-webkit-linear-gradient(right,white 54%, #709daf 46%)'; break;
        case '47': return '-webkit-linear-gradient(right,white 53%, #709daf 47%)'; break;
        case '48': return '-webkit-linear-gradient(right,white 52%, #709daf 48%)'; break;
        case '49': return '-webkit-linear-gradient(right,white 51%, #709daf 49%)'; break;
        case '50': return '-webkit-linear-gradient(right,white 50%, #709daf 50%)'; break;
        case '51': return '-webkit-linear-gradient(right,white 49%, #709daf 51%)'; break;
        case '52': return '-webkit-linear-gradient(right,white 48%, #709daf 52%)'; break;
        case '53': return '-webkit-linear-gradient(right,white 47%, #709daf 53%)'; break;
        case '54': return '-webkit-linear-gradient(right,white 46%, #709daf 54%)'; break;
        case '55': return '-webkit-linear-gradient(right,white 45%, #709daf 55%)';break;
        case '56': return '-webkit-linear-gradient(right,white 44%, #709daf 56%)'; break;
        case '57': return '-webkit-linear-gradient(right,white 43%, #709daf 57%)'; break;
        case '58': return '-webkit-linear-gradient(right,white 42%, #709daf 58%)'; break;
        case '59': return '-webkit-linear-gradient(right,white 41%, #709daf 59%)'; break;
        case '60': return '-webkit-linear-gradient(right,white 40%, #709daf 60%)'; break;
        case '61': return '-webkit-linear-gradient(right,white 39%, #709daf 61%)'; break;
        case '62': return '-webkit-linear-gradient(right,white 38%, #709daf 62%)'; break;
        case '63': return '-webkit-linear-gradient(right,white 37%, #709daf 63%)'; break;
        case '64': return '-webkit-linear-gradient(right,white 36%, #709daf 64%)'; break;
        case '65': return '-webkit-linear-gradient(right,white 35%, #709daf 65%)';break;
        case '66': return '-webkit-linear-gradient(right,white 34%, #709daf 66%)'; break;
        case '67': return '-webkit-linear-gradient(right,white 33%, #709daf 67%)'; break;
        case '68': return '-webkit-linear-gradient(right,white 32%, #709daf 68%)'; break;
        case '69': return '-webkit-linear-gradient(right,white 31%, #709daf 69%)'; break;
        case '70': return '-webkit-linear-gradient(right,white 30%, #709daf 70%)'; break;
        case '71': return '-webkit-linear-gradient(right,white 29%, #709daf 71%)'; break;
        case '72': return '-webkit-linear-gradient(right,white 28%, #709daf 72%)'; break;
        case '73': return '-webkit-linear-gradient(right,white 27%, #709daf 73%)'; break;
        case '74': return '-webkit-linear-gradient(right,white 26%, #709daf 74%)'; break;
        case '75': return '-webkit-linear-gradient(right,white 25%, #709daf 75%)';break;
        case '76': return '-webkit-linear-gradient(right,white 24%, #709daf 76%)'; break;
        case '77': return '-webkit-linear-gradient(right,white 23%, #709daf 77%)'; break;
        case '78': return '-webkit-linear-gradient(right,white 22%, #709daf 78%)'; break;
        case '79': return '-webkit-linear-gradient(right,white 21%, #709daf 79%)'; break;
        case '80': return '-webkit-linear-gradient(right,white 20%, #709daf 80%)'; break;
        case '81': return '-webkit-linear-gradient(right,white 19%, #709daf 81%)'; break;
        case '82': return '-webkit-linear-gradient(right,white 18%, #709daf 82%)'; break;
        case '83': return '-webkit-linear-gradient(right,white 17%, #709daf 83%)'; break;
        case '84': return '-webkit-linear-gradient(right,white 16%, #709daf 84%)'; break;
        case '85': return '-webkit-linear-gradient(right,white 15%, #709daf 85%)';break;
        case '86': return '-webkit-linear-gradient(right,white 14%, #709daf 86%)'; break;
        case '87': return '-webkit-linear-gradient(right,white 13%, #709daf 87%)'; break;
        case '88': return '-webkit-linear-gradient(right,white 12%, #709daf 88%)'; break;
        case '89': return '-webkit-linear-gradient(right,white 11%, #709daf 89%)'; break;
        case '90': return '-webkit-linear-gradient(right,white 10%, #709daf 90%)'; break;
        case '91': return '-webkit-linear-gradient(right,white 9%, #709daf 91%)'; break;
        case '92': return '-webkit-linear-gradient(right,white 8%, #709daf 92%)'; break;
        case '93': return '-webkit-linear-gradient(right,white 7%, #709daf 93%)'; break;
        case '94': return '-webkit-linear-gradient(right,white 6%, #709daf 94%)'; break;
        case '95': return '-webkit-linear-gradient(right,white 5%, #709daf 95%)';break;
        case '96': return '-webkit-linear-gradient(right,white 4%, #709daf 96%)'; break;
        case '97': return '-webkit-linear-gradient(right,white 3%, #709daf 97%)'; break;
        case '98': return '-webkit-linear-gradient(right,white 2%, #709daf 98%)'; break;
        case '99': return '-webkit-linear-gradient(right,white 1%, #709daf 99%)'; break;
        case '100': return '-webkit-linear-gradient(right,white 0%, #709daf 100%)'; break;
    };
}